name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    steps:
      - name: Generar variable
        id: step_1
        run: echo "my_variable=Hola Mundo" >> "$GITHUB_OUTPUT"

      - name: Mostrar variable local
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}
    steps:
      - name: Usar variable del primer job
        run: echo "Mensaje recibido: $SALIDA"